name: dart_shared_tools
description: A set of Dart tools I usually make use in my projects (no Flutter dependency).
version: 0.1.0
homepage: https://github.com/alexrintt/dart-shared-tools

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.4
